### ISSUE TITLE
Clicking on logo should redirect to homepage

### ISSUE THREAD

**Issue by nitinkgp23** [kossiitkgp/kossiitkgp.github.io#110]

**Comment by Ricardo-Silva91** [comment]
Hello, I made a pull request with a proposed solution for this issue (#115).
Feedback is welcome.

**Comment by americast** [comment]
@Ricardo-Silva91 I guess mentioning `Fixes #<issue no.>` in your PR comment helps auto-closing it. You had mentioned `fix for #<issue no.>`. Hence, I mentioned it separately in the PR comments while merging it. Thanx! :smile:
