### ISSUE TITLE
Meta tags in pages

### ISSUE THREAD

**Issue by djbarnwal** [kossiitkgp/kossiitkgp.github.io#14]
Meta tags such as keywords and description needs to be added in each page for SEO of the website. You may use a meta tags generator for this purpose. There are a lot of tags available but we need to add only essential ones such as - 
Titile
Keywords
Description

More tags can be added in case the developer thinks it is necessary.

**Comment by americast** [comment]
@harishnandan is working on it.

**Comment by americast** [comment]
Fixed in #40
