### ISSUE TITLE
Update Navbar and Footer links

### ISSUE THREAD

**Issue by djbarnwal** [kossiitkgp/kossiitkgp.github.io#15]
Currently we have dummy links in the header and footer section. We need to update the text and change the links. We also have to link to our Facebook page in the footer section.

**Comment by djbarnwal** [comment]
Also when someone works on this, he/she should remove the `index.html` from the URL, such that the URL looks like abc.com/events and not abc.com/events/index.html

**Comment by americast** [comment]
@dhiraj161298 I guess this can be achieved using the `<base>` tag.
