### ISSUE TITLE
Terminal not working @ https://kossiitkgp.in/terminal/index.html

### ISSUE THREAD

**Issue by piyushchauhan** [kossiitkgp/kossiitkgp.github.io#171]
Terminal @ https://kossiitkgp.in/terminal/index.html is not working.
The webpage at **https://webssh.bartlweb.net/** might be temporarily down or it may have moved permanently to a new web address.

**Comment by rakaar** [comment]
The link to the terminal has been removed from the navbar. 
Yes you are right `https://webssh.bartlweb.net/` has been removed
