### ISSUE TITLE
Divide Contributions Chart [suggestion]

### ISSUE THREAD

**Issue by Aniq55** [kossiitkgp/kossiitkgp.github.io#175]
The page stops responding when I tried to load the contributions page.
It'd be better if it's divided into multiple pages based on the rank.

**Comment by thealphadollar** [comment]
Hey @Aniq55 , we have updated the page to load more results as you scroll down towards the bottom. We will look to paginate as well but that will hinder the ability to sort all information at once in the frontend itself. 

Try to load the page again, the page should load now :)
