### ISSUE TITLE
Move footer in a separate HTML file

### ISSUE THREAD

**Issue by pranitbauva1997** [kossiitkgp/kossiitkgp.github.io#20]
Right now, if we need to make a change in the footer, we need to do this across all of our html files which is *bad* because:

- Too many changes to do
- One might forget to do a change in a part.

This also implies that we should have more modularity in our code. We can keep headers and footers in separate `headers.html` and `footers.html` and directly import them in all of our files. I agree this is refactoring work but this is seriously quite important otherwise we will have inconsistencies across our whole website. Please work on this immediately and get this done before doing other changes.

**Comment by pranitbauva1997** [comment]
See [this](https://www.html5rocks.com/en/tutorials/webcomponents/imports/) for reference on how to move forward with this.

**Comment by americast** [comment]
Anyone willing to fix this issue, please note that the changes requested should not be incorporated into `index.html` (the one which is present in the root) as it uses a different template. All other pages need to follow the aforementioned guideline.

**Comment by sipah00** [comment]
@americast ,I will  work on this.

**Comment by americast** [comment]
@sipah00 Cool! Go ahead.
