### ISSUE TITLE
Form for 'Contact us' page

### ISSUE THREAD

**Issue by americast** [kossiitkgp/kossiitkgp.github.io#27]
A form needs to be developed in the 'Contact Us' page. A backend implementation to receive the data and send it out as emails may also be built. We may keep the backend sleeping till a response is received.

Only the frontend part is to be designed here. The backend part has to be worked out in another repo: https://github.com/kossiitkgp/profile-generator/issues/4

For frontend, one may refer to: https://semantic-ui.com/collections/form.html
For sending emails using backend, reference may be taken from Flask-Mail: https://pythonhosted.org/Flask-Mail/

**Comment by dibyadas** [comment]
We can add this task to the flask backend we are working on. We can integrate a database and configure sendmail to send us an email whenever a form is filled up.
Can you assign this to me? I would love to take up this issue. :smile:

**Comment by americast** [comment]
@dibyadas Sorry. This issue cannot be assigned to you.

**Comment by dibyadas** [comment]
No worries. I think @aryan maybe willing to do it since he has experience working with SQLalchemy and is also working in the backend.

**Comment by aribis369** [comment]
@americast @dibyadas @aryan what I'm thinking that to store the credentials of users requiring to contact in a database and then define a subprocess in our program to send the emails at a particular period of time of the day.Till then our program of sending emails sleeps.What's your thoughts?

**Comment by dibyadas** [comment]
@americast I think we should separate the frontend part and the backend part, and add a link to the issue I have raised about the same in the profile-generator repo, here.

**Comment by americast** [comment]
@aribis369 I am not in favour of involving a DBMS to store the form data. I guess we could use Google Sheets instead. I think instantaneous sending of emails is required, in case something urgent is requested by someone.

**Comment by aribis369** [comment]
@americast Yes I discussed the same idea on slack to send emails instantaneously. Sending emails instantaneously may block the stream when traffic is large but we dont expect such a large traffic so no DBMS idea can be fixed. We are ready to work.

**Comment by dibyadas** [comment]
@aribis369 I agree with @americast. We won't have that much traffic that we would need to use a database as buffer. 
@americast since our backend is in flask, it makes sense to add this small feature in that app as well. So can you update the backend reference for this feature to Flask-Mail instead of php forms?

**Comment by americast** [comment]
@aribis369 is working on this.

**Comment by americast** [comment]
Fixed in PR #44
