### ISSUE TITLE
Extend the description Section: Events Page

### ISSUE THREAD

**Issue by vernwalrahul** [kossiitkgp/kossiitkgp.github.io#34]
Add further cards for other events like:
Ubuntu Installation Fest,
GSOC intro seminar,
Android Workshop,
Hackathon.

refer [kossiitkgp/events](http://kossiitkgp.in/events) for further details.

**Comment by americast** [comment]
@ashishkg0022 is working on it.

**Comment by ashishkg0022** [comment]
sorry i didn't see this issue .

**Comment by americast** [comment]
Fixed in #36
