### ISSUE TITLE
Add links to Help page

### ISSUE THREAD

**Issue by harishnandan** [kossiitkgp/kossiitkgp.github.io#47]
Help page cannot be reached through the links present in any page. The links need to be modified. Please place it just before the `Contact Us` page link.

**Comment by americast** [comment]
@harishnandan I dont think so: 
![2017-05-07-112417_1366x768_scrot](https://cloud.githubusercontent.com/assets/23132358/25778317/cfb7ddee-3317-11e7-9d37-a5fd6303138a.png)

**Comment by sipah00** [comment]
@americast ,I will work on this.

**Comment by americast** [comment]
@sipah00 Cool! Please go ahead.

**Comment by americast** [comment]
Fixed in #50.
