### ISSUE TITLE
Create individual pages for each event.

### ISSUE THREAD

**Issue by vernwalrahul** [kossiitkgp/kossiitkgp.github.io#51]
Check the sample template and modify it as per your event page, just the basic look must be same.
Please mention here the name of event you are working on.

Refer: [Sample Template](https://kossiitkgp.github.io/events/detail.html)

**Comment by tibrewalpratik17** [comment]
GSoC Seminar

**Comment by tibrewalpratik17** [comment]
ubuntu install fest and github workshop

**Comment by ashishkg0022** [comment]
Maker Party @KGP aka HTML 1.0 , Applied CS with Android workshop , MozSetup@IITKGP

**Comment by ankita132** [comment]
3D printing Workshop,Flipkart Hackathon,Game Development Workshop
