### ISSUE TITLE
Stop preloader repeat

### ISSUE THREAD

**Issue by americast** [kossiitkgp/kossiitkgp.github.io#59]
The preloader should only appear when the site is loaded from an external page. It should not get repeated when one views the home page by clicking on the `Home` button of an internal page.

**Comment by harishnandan** [comment]
Moreover the preloader does not end smoothly in Mozilla Firefox. Please modify it too.
![screenshot from 2017-05-09 11-46-35](https://cloud.githubusercontent.com/assets/24224542/25838039/743edf0c-3480-11e7-8c53-8dfa1066ee96.png)

**Comment by americast** [comment]
@harishnandan It appears fine for me though. I guess it's because you have provided less width to Firefox by having an "always-floating" panel on the left. Still, a fix is necessary I guess.
