### ISSUE TITLE
Incorporate spam filter in contact form

### ISSUE THREAD

**Issue by americast** [kossiitkgp/kossiitkgp.github.io#60]
Nocaptcha recaptcha should be a part of the contact form to do away with spammers.

**Comment by kaustubhhiware** [comment]
@americast Not possibly my place to say, but you can use https://formspree.io . It has some level of authentication. IIRC, it's being used in Swarm-iitkgp's website as well.

**Comment by americast** [comment]
@kaustubhhiware Thanx a lot for pointing us to such a wonderful resource :smile: ! We would definitely explore this option. Also, it would be great if you could highlight the benefits of using Formspree over maintaining our own backend to handle this.

**Comment by kaustubhhiware** [comment]
I have used formspree.io on my website as well, and the only thing you need is to add a form after registering on formspree. This removes the need of a backend logic altogether. I'm not sure why, but formspree has one of the two validation schemes:
* I'm not a robot button
* A random image captcha to solve

What kind of backend is currently set in place ? If the backend also deals with other things, then no need to use it, but if the backend handles only the contact us form, recommend using formspree

**Comment by americast** [comment]
@kaustubhhiware The backend is currently under development. The "other things" which we have planned to use it for is to keep a record of all form entries in Google Sheets.

**Comment by dibyadas** [comment]
@americast @kaustubhhiware The backend also generates profile pages for each member from a predefined template. I had a look at that Formspree. It's great!. But I'm reluctant to use that. Partly because I spent quite some time making that contact us form :p . And partly because, if we use Formspree , where's the fun in that ;)

**Comment by aribis369** [comment]
@dibyadas @americast It may be a bad idea now after all that effort being put in the contact us us page but we have flask add-on i.e. FlaskWTF having catcha validating technique built in. But I think any other thing could be found out for our existing code. If nothing's found out we can go for FlaskWTF.

**Comment by dibyadas** [comment]
@aribis369 No worries. Adding Google's recaptcha won't be that difficult .

**Comment by aribis369** [comment]
yep that could be done it didn't come to my mind.
seen it's library very easy to implement. It's PSF webpage describes it as a alternative of FlaskWTF .

**Comment by dibyadas** [comment]
I'm taking this up. @americast Can you assign this to me?

**Comment by americast** [comment]
@dibyadas Cool! Go ahead!
